// Builds the store packages:
//   dist/chrome/, dist/edge-store/, dist/firefox/   unpacked builds, for loading into the browser to test
//   dist/anydownload-<version>-<target>.zip         what gets uploaded to each store
// manifest.json in the repo works unpacked in both browsers; each build gets a copy trimmed to
// the keys its browser understands, so the store linters don't flag the other browser's keys.
// chrome is the Chromium build that's loaded unpacked, with the update checker in updater/ added.
// edge-store is the Chromium build with the changes Edge Add-ons needs on top.
//
// Usage: npm run package   (needs `zip` on the PATH, and libs/ from `npm install`)

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join(import.meta.dirname, '..');
const DIST = path.join(ROOT, 'dist');
// everything the extension loads at runtime; the rest of the repo is build tooling
const FILES = ['background.js', 'rpc.js', 'core', 'pages', 'logo', 'libs', 'LICENSE.txt', 'THIRD_PARTY_LICENSES.txt'];
const JUNK = new Set(['.DS_Store', 'Thumbs.db', 'desktop.ini']);
// zip stores timestamps, so give every file the same one to make rebuilds byte-identical
const MTIME = new Date('2020-01-01T00:00:00Z');

const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));
const readVendor = (file) => JSON.parse(fs.readFileSync(file, 'utf8').replace(/^[^]*?self\.VENDOR = /, '').replace(/;\s*$/, ''));

function chromium(manifest) {
    delete manifest.browser_specific_settings;
    manifest.background = { service_worker: manifest.background.service_worker };
}

// replaces `from` in a copied file, which has to contain it
function patch(file, from, to) {
    const src = fs.readFileSync(file, 'utf8');
    if (!src.includes(from)) throw new Error(`${path.relative(ROOT, file)} no longer contains ${JSON.stringify(from)}`);
    fs.writeFileSync(file, src.replace(from, () => to));
    fs.utimesSync(file, MTIME, MTIME);
}

// Chrome never updates an extension loaded unpacked, as the chrome build is, so that build checks
// GitHub for new releases itself. A store's builds are updated by the store.
function addUpdater(dir, files) {
    files.push(...copy('updater', dir));
    // the panel's update notice
    const script = '<script src="iframe.js"></script>';
    patch(path.join(dir, 'core/iframe/iframe.html'), script,
        `${script}\n    <script src="/updater/check.js"></script>\n    <script src="/updater/panel.js"></script>`);
}

function chromeWithUpdater(manifest) {
    chromium(manifest);
    // background.js, then the update checks
    manifest.background.service_worker = 'updater/service-worker.js';
}

// Edge Add-ons rejects packages with an archive inside, and Pyodide's stdlib is a zip. Pyodide only
// fetches its bytes, so it doesn't care what the file is called: ship it as .bin instead.
function renameStdlib(dir, files) {
    const vendorFile = path.join(dir, 'libs', 'vendor.js');
    const vendor = readVendor(vendorFile);
    const from = vendor.stdlib;
    const to = from.replace(/\.zip$/, '.bin');
    fs.renameSync(path.join(dir, from), path.join(dir, to));
    files[files.indexOf(from.slice(1))] = to.slice(1);

    vendor.stdlib = to;
    fs.writeFileSync(vendorFile, `// Generated by scripts/vendor.mjs and scripts/package.mjs, do not edit.\nself.VENDOR = ${JSON.stringify(vendor, null, 4)};\n`);
    fs.utimesSync(vendorFile, MTIME, MTIME);
}

// manifest: trims the manifest for the target's browser, files: changes to the copied files, if any
const TARGETS = {
    chrome: { manifest: chromeWithUpdater, files: addUpdater },
    'edge-store': { manifest: chromium, files: renameStdlib },
    firefox: {
        manifest(manifest) {
            // Firefox runs background.scripts as an event page and ignores service_worker
            manifest.background = { scripts: manifest.background.scripts };
            // Chrome's and Edge's (their versions match): 137 is the first with JSPI (WebAssembly.Suspending),
            // which Pyodide's run_sync needs. Firefox's minimum is in browser_specific_settings.
            delete manifest.minimum_chrome_version;
        },
    },
};

// libs/ is generated, so make sure it was built from the pins currently in the repo
function checkLibs() {
    const vendorFile = path.join(ROOT, 'libs', 'vendor.js');
    if (!fs.existsSync(vendorFile)) throw new Error('libs/ is missing. Run `npm install` first.');
    const { versions, stdlib } = readVendor(vendorFile);
    if (!stdlib) throw new Error('libs/vendor.js is out of date. Run `npm run vendor`.');
    const wanted = { ...readJson(path.join(ROOT, 'package.json')).dependencies };
    for (const line of fs.readFileSync(path.join(ROOT, 'requirements.txt'), 'utf8').split('\n')) {
        const m = /^([A-Za-z0-9._-]+)\s*==\s*([^\s;#]+)/.exec(line);
        if (m) wanted[m[1]] = m[2];
    }
    for (const [name, version] of Object.entries(wanted)) {
        if (versions[name] !== version) {
            throw new Error(`libs/ has ${name} ${versions[name] ?? '(missing)'} but ${version} is pinned. Run \`npm run vendor\`.`);
        }
    }
    return versions;
}

// every vendored library has to be credited in THIRD_PARTY_LICENSES.txt before it ships
function checkLicenses(vendored) {
    const notices = fs.readFileSync(path.join(ROOT, 'THIRD_PARTY_LICENSES.txt'), 'utf8').toLowerCase();
    const missing = Object.keys(vendored).filter((name) => !notices.includes(name.toLowerCase()));
    if (missing.length) throw new Error(`THIRD_PARTY_LICENSES.txt doesn't mention ${missing.join(', ')}. Add their licenses to it.`);
}

// copies `rel` from the repo into `dir`, returning the files copied as zip paths
function copy(rel, dir) {
    const from = path.join(ROOT, rel);
    if (fs.statSync(from).isDirectory()) {
        return fs.readdirSync(from)
            .filter((name) => !JUNK.has(name))
            .flatMap((name) => copy(path.join(rel, name), dir));
    }
    const to = path.join(dir, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    fs.utimesSync(to, MTIME, MTIME);
    return [rel.split(path.sep).join('/')];
}

function zip(dir, files, out) {
    try {
        // -X: no OS-specific extra fields, -D: no directory entries, -@: file list from stdin
        execFileSync('zip', ['-q', '-X', '-D', '-9', out, '-@'], {
            cwd: dir,
            input: files.join('\n'),
            // zip stores local time, so pin the zone or the timestamps depend on where it's built
            env: { ...process.env, TZ: 'UTC' },
            stdio: ['pipe', 'inherit', 'inherit'],
        });
    } catch (e) {
        if (e.code === 'ENOENT') throw new Error('`zip` was not found. Install it and make sure it is on your PATH.');
        throw e;
    }
}

checkLicenses(checkLibs());
const base = readJson(path.join(ROOT, 'manifest.json'));
fs.rmSync(DIST, { recursive: true, force: true });

for (const [target, adapt] of Object.entries(TARGETS)) {
    const dir = path.join(DIST, target);
    const files = FILES.flatMap((rel) => copy(rel, dir));
    adapt.files?.(dir, files);
    // a store build offering GitHub's zip would install a second, unpacked copy next to the store's
    if (target !== 'chrome' && files.some((file) => file.startsWith('updater/'))) {
        throw new Error(`the ${target} build mustn't include the update checker`);
    }

    const manifest = structuredClone(base);
    adapt.manifest(manifest);
    fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
    fs.utimesSync(path.join(dir, 'manifest.json'), MTIME, MTIME);
    files.push('manifest.json');

    const out = path.join(DIST, `anydownload-${base.version}-${target}.zip`);
    zip(dir, files.sort(), out);
    console.log(`${target}: ${path.relative(ROOT, out)} (${(fs.statSync(out).size / 1024 / 1024).toFixed(1)} MB, ${files.length} files)`);
}
